name = "Pot8o"
uuid = "b2da7a4a-07ab-44dc-8b32-6aee5ecfc0dc"
authors = ["Leo Basov <basov.leo@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
